# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 3000, 3000))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Status_tab = QtWidgets.QWidget()
        self.Status_tab.setObjectName("Status_tab")
        self.label = QtWidgets.QLabel(self.Status_tab)
        self.label.setGeometry(QtCore.QRect(280, 60, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.Status_tab)
        self.tableWidget.setGeometry(QtCore.QRect(210, 170, 341, 51))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.Update_btn = QtWidgets.QPushButton(self.Status_tab)
        self.Update_btn.setGeometry(QtCore.QRect(340, 260, 75, 23))
        self.Update_btn.setObjectName("Update_btn")
        self.tabWidget.addTab(self.Status_tab, "")
        self.Append_tab = QtWidgets.QWidget()
        self.Append_tab.setObjectName("Append_tab")
        self.label_2 = QtWidgets.QLabel(self.Append_tab)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 421, 151))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.Append_tab)
        self.groupBox.setGeometry(QtCore.QRect(240, 130, 301, 351))
        self.groupBox.setObjectName("groupBox")
        self.breed = QtWidgets.QComboBox(self.groupBox)
        self.breed.setGeometry(QtCore.QRect(90, 80, 91, 21))
        self.breed.setObjectName("breed")
        self.breed.addItem("")
        self.breed.addItem("")
        self.breed.addItem("")
        self.breed.addItem("")
        self.breed.addItem("")
        self.breed.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 71, 21))
        self.label_5.setObjectName("label_5")
        self.pet_name = QtWidgets.QLineEdit(self.groupBox)
        self.pet_name.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.pet_name.setObjectName("pet_name")
        self.date_born = QtWidgets.QDateEdit(self.groupBox)
        self.date_born.setGeometry(QtCore.QRect(90, 110, 110, 22))
        self.date_born.setObjectName("date_born")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 71, 21))
        self.label_6.setObjectName("label_6")
        self.sex = QtWidgets.QComboBox(self.groupBox)
        self.sex.setGeometry(QtCore.QRect(90, 140, 91, 21))
        self.sex.setObjectName("sex")
        self.sex.addItem("Męska")
        self.sex.addItem("Żeńska")
        self.pet_name_unknow = QtWidgets.QCheckBox(self.groupBox)
        self.pet_name_unknow.setGeometry(QtCore.QRect(220, 50, 70, 17))
        self.pet_name_unknow.setObjectName("pet_name_unknow")
        self.breed_unknow = QtWidgets.QCheckBox(self.groupBox)
        self.breed_unknow.setGeometry(QtCore.QRect(220, 80, 70, 17))
        self.breed_unknow.setObjectName("breed_unknow")
        self.date_born_unknow = QtWidgets.QCheckBox(self.groupBox)
        self.date_born_unknow.setGeometry(QtCore.QRect(220, 110, 70, 17))
        self.date_born_unknow.setObjectName("date_born_unknow")
        self.Append_btn = QtWidgets.QPushButton(self.groupBox)
        self.Append_btn.setGeometry(QtCore.QRect(210, 180, 75, 23))
        self.Append_btn.setObjectName("Append_btn")
        self.tabWidget.addTab(self.Append_tab, "")
        self.Remove_tab = QtWidgets.QWidget()
        self.Remove_tab.setObjectName("Remove_tab")
        self.tabWidget.addTab(self.Remove_tab, "")
        self.Base_tab = QtWidgets.QWidget()
        self.Base_tab.setObjectName("Base_tab")
        self.tabWidget.addTab(self.Base_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Status schroniska"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ilość"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Wolne miejsca"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Zwierzęta"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Wszystkich miejsc"))
        self.Update_btn.setText(_translate("MainWindow", "Aktualizuj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Status_tab), _translate("MainWindow", "Status"))
        self.label_2.setText(_translate("MainWindow", "Wypełnij następujące informacje"))
        self.groupBox.setTitle(_translate("MainWindow", "Dane"))
        self.breed.setItemText(0, _translate("MainWindow", "New Item"))
        self.breed.setItemText(1, _translate("MainWindow", "New Item"))
        self.breed.setItemText(2, _translate("MainWindow", "New Item"))
        self.breed.setItemText(3, _translate("MainWindow", "New Item"))
        self.breed.setItemText(4, _translate("MainWindow", "New Item"))
        self.breed.setItemText(5, _translate("MainWindow", "New Item"))
        self.label_3.setText(_translate("MainWindow", "Nazwa pupila"))
        self.label_4.setText(_translate("MainWindow", "Rasa"))
        self.label_5.setText(_translate("MainWindow", "Data urodzenia"))
        self.label_6.setText(_translate("MainWindow", "Płeć"))
        self.sex.setItemText(0, _translate("MainWindow", "Męska"))
        self.sex.setItemText(1, _translate("MainWindow", "Żeńska"))
        self.sex.setItemText(2, _translate("MainWindow", "New Item"))
        self.pet_name_unknow.setText(_translate("MainWindow", "Nieznane"))
        self.breed_unknow.setText(_translate("MainWindow", "Nieznane"))
        self.date_born_unknow.setText(_translate("MainWindow", "Nieznane"))
        self.Append_btn.setText(_translate("MainWindow", "Dodaj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Append_tab), _translate("MainWindow", "Dodaj"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Remove_tab), _translate("MainWindow", "Usun"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Base_tab), _translate("MainWindow", "Baza"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


