# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import mysql.connector


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import mysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 3000, 3000))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setGeometry(QtCore.QRect(440, 190, 481, 121))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(560, 360, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setGeometry(QtCore.QRect(560, 340, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setGeometry(QtCore.QRect(560, 390, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(560, 410, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(690, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.tabs = QtWidgets.QTabWidget(self.page_2)
        self.tabs.setEnabled(True)
        self.tabs.setGeometry(QtCore.QRect(0, 0, 3000, 3000))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabs.setFont(font)
        self.tabs.setToolTipDuration(-2)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.setObjectName("tabs")
        self.tab_dodaj_4 = QtWidgets.QWidget()
        self.tab_dodaj_4.setObjectName("tab_dodaj_4")
        self.label_4 = QtWidgets.QLabel(self.tab_dodaj_4)
        self.label_4.setGeometry(QtCore.QRect(310, 150, 681, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_dodaj_4)
        self.scrollArea_4.setGeometry(QtCore.QRect(290, 350, 161, 71))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 159, 69))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.listWidget_4 = QtWidgets.QListWidget(self.tab_dodaj_4)
        self.listWidget_4.setGeometry(QtCore.QRect(670, 310, 256, 192))
        self.listWidget_4.setObjectName("listWidget_4")
        self.tabs.addTab(self.tab_dodaj_4, "")
        self.tab_usun_4 = QtWidgets.QWidget()
        self.tab_usun_4.setObjectName("tab_usun_4")
        self.tabs.addTab(self.tab_usun_4, "")
        self.tab_status_4 = QtWidgets.QWidget()
        self.tab_status_4.setObjectName("tab_status_4")
        self.tabs.addTab(self.tab_status_4, "")
        self.tab_baza_4 = QtWidgets.QWidget()
        self.tab_baza_4.setObjectName("tab_baza_4")
        self.tabs.addTab(self.tab_baza_4, "")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 21))
        self.menubar.setObjectName("menubar")
        self.menuelo = QtWidgets.QMenu(self.menubar)
        self.menuelo.setObjectName("menuelo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuelo.menuAction())
        self.pushButton.clicked.connect(self.change_page)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def change_page(self):
        self.stackedWidget.setCurrentIndex(1)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Zaloguj się do schroniska!"))
        self.label_6.setText(_translate("MainWindow", "Login"))
        self.label_7.setText(_translate("MainWindow", "Haslo"))
        self.pushButton.setText(_translate("MainWindow", "Zaloguj"))
        self.label_4.setText(_translate("MainWindow", "Jakie psa chcesz dodać do schronika?"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_dodaj_4), _translate("MainWindow", "Dodaj"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_usun_4), _translate("MainWindow", "Usun"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_status_4), _translate("MainWindow", "Status"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab_baza_4), _translate("MainWindow", "Baza"))
        self.menuelo.setTitle(_translate("MainWindow", "File"))



